version: "3.9"
services:
  bot:
    container_name: weigandt-gpt-slack-bot
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /usr/gptslackbot/logs:/usr/gptslackbot/logs
      - /usr/gptslackbot/ssl:/usr/gptslackbot/ssl
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    restart: always
    env_file: mongo.env
    ports:
      - "27017:27017"
    volumes:
      - /usr/gptslackbot/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - /usr/gptslackbot/mongodata:/data/db
      - /usr/gptslackbot/mongologs:/var/log/mongodb
