version: "3.9"
services:
  bot:
    container_name: weigandt-gpt-slack-bot
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /usr/gptslackbot/logs:/usr/gptslackbot/logs
      - /usr/gptslackbot/ssl:/usr/gptslackbot/ssl
