logging.level:
  com.slack.api: DEBUG
spring:
  profiles:
    active:

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 3000
  ssl:
    key-store:
    key-store-password:
    key-store-type: pkcs12
    key-alias: gptslackbot
    key-password:

openai:
  apikey:
  qa:
    model: gpt-3.5-turbo
    threshold:
      soft: 3000
      hard: 10000

chat:
  history:
    limit: 6
    base:
      path: ./logs
    max:
      size: 5Mb
