logging.level:
  com.slack.api: DEBUG
server:
  port: 3000
  ssl:
    key-store: classpath:gptslackbot.p12
    key-store-password:
    key-store-type: pkcs12
    key-alias: gptslackbot
    key-password:

openai:
  apikey:
  embeddings:
    model: text-embedding-ada-002
  qa:
    model: gpt-3.5-turbo

pinecone:
  apikey: 
  index:
    name: test-embeddings
  environment: us-west4-gcp
  project:
    name: 0eba6a6
  namespace: docs-ns
  topK: 2

file:
  processor:
    chunk:
      size: 30
    overlap: 10
chat:
  history:
    base:
      path: ./logs
    max:
      size: 5Mb